# Generated by Django 3.2.7 on 2021-09-14 09:58

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(default='img.jpg', max_length=255, verbose_name='image')),
                ('bio', models.TextField(default='Add Bio here')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('caption', models.TextField(default='caption')),
                ('comments', models.TextField(default='comment here')),
                ('photo', cloudinary.models.CloudinaryField(default='photo.jpeg', max_length=255, verbose_name='image')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(default='photo&bio', on_delete=django.db.models.deletion.CASCADE, to='phiimages.profile')),
            ],
        ),
    ]
