# Generated by Django 3.2.7 on 2021-09-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phiimages', '0005_alter_image_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='author',
            new_name='username',
        ),
    ]
